---
version: "3.9"
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "80:80"
      - "8080:8080"
    command: 'nginx -g "daemon off;"'
    depends_on:
      - test-color-app

  test-color-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: test-color-app
    working_dir: /app
    ports:
      - "127.0.0.1:5000:5000"
