name: Preview

on: workflow_dispatch

jobs:
  prepare:
    runs-on: self-hosted
    name: Setup environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

  build:
    needs: prepare
    runs-on: self-hosted
    name: Build and push to registry
    environment: Preview
    steps:
      - name: Build and push to registry
        env:
          VERSION_FILE: ${{ env.VERSION_FILE }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          REGISTRY_USERNAME: ${{ env.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_NAME: ${{ env.REGISTRY_NAME }}
        run: nix-shell

  test:
    needs: build
    runs-on: self-hosted
    name: Test
    steps:
      - name: test
        run: ls -lah ; cat .bumpverison.toml
