name: Preview create

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: self-hosted
    name: Setup environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

  build:
    needs: prepare
    runs-on: self-hosted
    name: Build and push to registry
    env:
      DEPLOYMENT_ENV: "preview"
      VERSION: ${{ github.run_id }}
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      REGISTRY_NAME: ${{ vars.REGISTRY_NAME }}
    steps:
      - name: Build and push to registry
        run: nix-shell
